version: '3'
services:
  db-cats-api:
    image: postgres:16
    restart: always
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cats-api